// TODO REDUCER CONSTANTS
export const TODO_CREATE_TODO_IN_PROGRESS = "TODO_CREATE_TODO_IN_PROGRESS";
export const TODO_CREATE_TODO_SUCCESS = "TODO_CREATE_TODO_SUCCESS";
export const TODO_CREATE_TODO_FAILED = "TODO_CREATE_TODO_Failed";

export const TODO_COMPLETED_IN_PROGRESS = "TODO_COMPLETED_IN_PROGRESS";
export const TODO_COMPLETED_SUCCESS = "TODO_COMPLETED_SUCCESS";
export const TODO_COMPLETED_FAILED = "TODO_COMPLETED_FAILED";

export const TODO_UPDATED_IN_PROGRESS = "TODO_UPDATED_IN_PROGRESS";
export const TODO_UPDATED_SUCCESS = "TODO_UPDATED_SUCCESS";
export const TODO_UPDATED_FAILED = "TODO_UPDATED_FAILED";

export const TODO_REMOVED_IN_PROGRESS = "TODO_REMOVED_IN_PROGRESS";
export const TODO_REMOVED_SUCCESS = "TODO_REMOVED_SUCCESS";
export const TODO_REMOVED_FAILED = "TODO_REMOVED_FAILED";

// HABITS REDUCER CONSTANTS
export const HABIT_CREATE_IN_PROGRESS = "HABIT_CREATE_IN_PROGRESS";
export const HABIT_CREATE_SUCCESS = "HABIT_CREATE_SUCCESS";
export const HABIT_CREATE_FAILED = "HABIT_CREATE_Failed";

export const HABIT_UPDATE_IN_PROGRESS = "HABIT_UPDATE_IN_PROGRESS";
export const HABIT_UPDATE_SUCCESS = "HABIT_UPDATE_SUCCESS";
export const HABIT_UPDATE_FAILED = "HABIT_UPDATE_FAILED";

export const HABIT_REMOVE_IN_PROGRESS = "HABIT_REMOVE_IN_PROGRESS";
export const HABIT_REMOVE_SUCCESS = "HABIT_REMOVE_SUCCESS";
export const HABIT_REMOVE_FAILED = "HABIT_REMOVE_FAILED";

// REMINDER REDUCER CONSTANTS
export const REMINDER_TIMER = "REMINDER_TIMER";
